sanup/config/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from account import views
from config import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard', views.dashboard, name='dashboard'),
    url(r'^pjs1234', views.pjs1234),
    url(r'^$', views.login_site, name='login_site'),
    url(r'^server/', views.server, name='server'),
    url(r'^signup', views.signUo, name='signup'),
    url(r'^logout', views.logout_site, name='logout_site'),
    url(r'^design_data/', include('design_data.urls', namespace='design_data')),
    url(r'^order/', include('order.urls', namespace='order')),
    url(r'^setting/', include('setting.urls', namespace='setting')),
    url(r'^material/', include('materials.urls', namespace='material')),
    url(r'^schedule/', include('schedule.urls', namespace='schedule')),
    url(r'^machine/', include('machine.urls', namespace='machine')),
    url(r'^production/', include('production.urls', namespace='production')),
    #url(r'^ordercheack$', views.ordercheack),
]



urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

sanup/design_data/urls.py
from django.conf.urls import url, include
from django.views.decorators.csrf import csrf_exempt
from rest_framework import routers

from design_data import views
app_name = 'design_data'

router = routers.DefaultRouter()
router.register(r'design_data_api', views.Design_data_api, basename='design_data_apis')

urlpatterns = [
    url(r'^upload$', csrf_exempt(views.upload)),
    url(r'^designdata$', csrf_exempt(views.designDataByJson)),
    url(r'^delete$', csrf_exempt(views.delete)),
    url(r'^getList$', csrf_exempt(views.designListByJson)),
    url(r'^detail/(?P<designId>\d+)$', views.showDesign),
    url(r'^design/(?P<designId>\d+)$', views.showDesignProduction),
    url(r'^$', csrf_exempt(views.showList)),
    url(r'^design_data_api/', include(router.urls, 'Design_data_api'), name='Design_data_api'),
]

sanup/order/urls.py
from django.conf.urls import url, include
from django.views.decorators.csrf import csrf_exempt
from . import views
from rest_framework import routers

app_name = 'order'

router = routers.DefaultRouter()
router.register(r'order_design_data', views.Order_design_data_api, basename='order_design_data_apis')
router1 = routers.DefaultRouter()
router1.register(r'order_data', views.Order_api, basename='order_data_apis')

urlpatterns = [
    url(r'^rawroll/(?P<id>\d+)', views.rawroll),
    url(r'^warpWorkSheet/(?P<id>\d+)', views.warpTable),
    url(r'^modify$', views.modifyOrder),
    url(r'^delete$', views.delete),
    url(r'^$', views.order),
    url(r'^list$', views.getOrderListByJson),
    url(r'^detail/(?P<orderId>\d+)', views.getOrderByJson),
    url(r'^showQr/(?P<id>\d+)', views.showQr),
    url(r'^subOrderJson/(?P<id>\d+)', views.getSubOrderByJson),
    url(r'^ordercheack$', views.ordercheack),
    url(r'^design_api/', include(router.urls, 'Order_design'), name='design_api'),
    url(r'^order_api/', include(router1.urls, 'Order'), name='order_api'),
]

sanup/design_data/models.py
from django.db import models


def upload_product_file(instance, filename):
    return filename


class FSTY_CAD_Design_Data(models.Model):
    CAD_Design_Data_id = models.AutoField(primary_key=True)
    CAD_Design_Data_name = models.CharField(max_length=100, null=True)
    CAD_Design_Data_code = models.CharField(max_length=100, null=True)
    CAD_Design_Data_xml = models.FileField(upload_to=upload_product_file, null=True)
    CAD_Design_Data_pattern_image = models.ImageField(upload_to=upload_product_file, null=True)
    CAD_Design_Data_simulation_image = models.ImageField(upload_to=upload_product_file, null=True)
    CAD_Design_Data_create_date = models.DateTimeField(auto_now_add=True, blank=True)
    CAD_Design_Data_trc_file = models.FileField(upload_to=upload_product_file, null=True)
    CAD_Design_Data_magnification = models.CharField(max_length=10, null=True, blank=True)

    class Meta:
        db_table = 'FSTY_CAD_Design_Data'

    def __str__(self):
        return self.CAD_Design_Data_name


class FSTY_CAD_Production(models.Model):
    CAD_Production_id = models.AutoField(primary_key=True)
    CAD_Production_quota_per_day = models.CharField(max_length=100, null=True)
    CAD_Production_machine_name = models.CharField(max_length=100, null=True)
    CAD_Production_note = models.CharField(max_length=100, null=True)
    CAD_Production_design_data = models.OneToOneField(FSTY_CAD_Design_Data, on_delete=models.CASCADE, null=True)

    class Meta:
        db_table = 'FSTY_CAD_Production'


class FSTY_CAD_Fabric(models.Model):
    CAD_Fabric_id = models.AutoField(primary_key=True)
    fabric_type = (
        ('R', u'row'),
        ('S', u'simulated')
    )
    CAD_Fabric_type = models.CharField(max_length=1, choices=fabric_type, null=True)
    CAD_Fabric_wpi = models.CharField(max_length=100, null=True)
    CAD_Fabric_cpi = models.CharField(max_length=100, null=True)
    CAD_Fabric_width = models.CharField(max_length=100, null=True)
    CAD_Fabric_weight_per_width = models.CharField(max_length=100, null=True)
    CAD_Fabric_production = models.ForeignKey(FSTY_CAD_Production, on_delete=models.CASCADE, null=True)

    class Meta:
        db_table = 'FSTY_CAD_Fabric'


class FSTY_CAD_Layer(models.Model):
    CAD_Layer_id = models.AutoField(primary_key=True)
    CAD_Layer_name = models.CharField(max_length=100, null=True)
    CAD_Layer_ratio = models.CharField(max_length=100, null=True)
    CAD_Layer_mm_rack = models.CharField(max_length=100, null=True)
    CAD_Layer_use = models.CharField(max_length=100, null=True)
    CAD_Layer_beam = models.CharField(max_length=100, null=True)
    CAD_Layer_total = models.CharField(max_length=100, null=True)
    CAD_Layer_iodata = models.CharField(max_length=2000, null=True)
    CAD_Layer_design_data = models.ForeignKey(FSTY_CAD_Design_Data, on_delete=models.CASCADE, null=True)

    class Meta:
        db_table = 'FSTY_CAD_Layer'


class FSTY_CAD_Yarn(models.Model):
    CAD_Yarn_id = models.AutoField(primary_key=True)
    CAD_Yarn_idx = models.CharField(max_length=100, null=True)
    CAD_Yarn_maker = models.CharField(max_length=100, null=True)
    CAD_Yarn_spec = models.CharField(max_length=100, null=True)
    CAD_Yarn_code = models.CharField(max_length=100, null=True)
    CAD_Yarn_rgb_color = models.CharField(max_length=100, null=True)
    CAD_Yarn_lab_color = models.CharField(max_length=100, null=True)
    CAD_Yarn_pantone_color = models.CharField(max_length=100, null=True)
    CAD_Yarn_layer = models.OneToOneField(FSTY_CAD_Layer, on_delete=models.CASCADE, null=True)


    class Meta:
        db_table = 'FSTY_CAD_Yarn'


class FSTY_CAD_Chain_Link(models.Model):
    CAD_Chain_Link_id = models.AutoField(primary_key=True)
    CAD_Chain_Link_course = models.CharField(max_length=2000)
    CAD_Chain_Link_layer = models.OneToOneField(FSTY_CAD_Layer, on_delete=models.CASCADE, null=True)


    class Meta:
        db_table = 'FSTY_CAD_Chain_Link'

sanup/design_data/views.py
import json

from django.contrib.auth.decorators import login_required
from django.core.files.base import ContentFile
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from xml.etree.ElementTree import parse
from .serializer import *

from django.views.generic import DetailView
from rest_framework import viewsets

import config.settings as settings
from design_data.models import *

from django.shortcuts import render, redirect
from order.models import *
from design_data.url_image_upload import url_image_upload
#from design_data.style_for_us_image_upload import style_for_us_image_upload


@csrf_exempt
def designDataByJson(request):
    jsonDesignObj = {}
    designId = request.POST.get('designId', None)
    designObj = FSTY_CAD_Design_Data.objects.get(CAD_Design_Data_id=designId)
    layerList = FSTY_CAD_Layer.objects.filter(CAD_Layer_design_data=designObj)
    fabricList = FSTY_CAD_Fabric.objects.filter(CAD_Fabric_production=designObj.fsty_cad_production)

    jsonFabricList = []
    for fabricObj in fabricList:
        jsonFabricObj = {}
        jsonFabricObj['CAD_Fabric_id'] = fabricObj.CAD_Fabric_id
        jsonFabricObj['CAD_Fabric_type'] = fabricObj.CAD_Fabric_type
        jsonFabricObj['CAD_Fabric_wpi'] = fabricObj.CAD_Fabric_wpi
        jsonFabricObj['CAD_Fabric_cpi'] = fabricObj.CAD_Fabric_cpi
        jsonFabricObj['CAD_Fabric_width'] = fabricObj.CAD_Fabric_width
        jsonFabricObj['CAD_Fabric_weight_per_width'] = fabricObj.CAD_Fabric_weight_per_width
        jsonFabricList.append(jsonFabricObj)

    jsonLayerList = []
    for layerObj in layerList:
        jsonLayerObj = {}
        jsonLayerObj['CAD_Layer_id'] = layerObj.CAD_Layer_id
        jsonLayerObj['CAD_Layer_name'] = layerObj.CAD_Layer_name
        jsonLayerObj['CAD_Layer_ratio'] = layerObj.CAD_Layer_ratio
        jsonLayerObj['CAD_Layer_mm_rack'] = layerObj.CAD_Layer_mm_rack
        jsonLayerObj['CAD_Layer_use'] = layerObj.CAD_Layer_use
        jsonLayerObj['CAD_Layer_beam'] = layerObj.CAD_Layer_beam
        jsonLayerObj['CAD_Layer_total'] = layerObj.CAD_Layer_total
        jsonLayerObj['CAD_Layer_iodata'] = layerObj.CAD_Layer_iodata
        jsonLayerObj['FSTY_CAD_Yarn'] = {}
        jsonLayerObj['FSTY_CAD_Yarn']['CAD_Yarn_id'] = layerObj.fsty_cad_yarn.CAD_Yarn_id
        jsonLayerObj['FSTY_CAD_Yarn']['CAD_Yarn_idx'] = layerObj.fsty_cad_yarn.CAD_Yarn_idx
        jsonLayerObj['FSTY_CAD_Yarn']['CAD_Yarn_maker'] = layerObj.fsty_cad_yarn.CAD_Yarn_maker
        jsonLayerObj['FSTY_CAD_Yarn']['CAD_Yarn_spec'] = layerObj.fsty_cad_yarn.CAD_Yarn_spec
        jsonLayerObj['FSTY_CAD_Yarn']['CAD_Yarn_code'] = layerObj.fsty_cad_yarn.CAD_Yarn_code
        jsonLayerObj['FSTY_CAD_Yarn']['CAD_Yarn_rgb_color'] = layerObj.fsty_cad_yarn.CAD_Yarn_rgb_color
        jsonLayerObj['FSTY_CAD_Yarn']['CAD_Yarn_lab_color'] = layerObj.fsty_cad_yarn.CAD_Yarn_lab_color
        jsonLayerObj['FSTY_CAD_Yarn']['CAD_Yarn_pantone_color'] = layerObj.fsty_cad_yarn.CAD_Yarn_pantone_color
        jsonLayerObj['FSTY_CAD_Chain_Link'] = {}
        jsonLayerObj['FSTY_CAD_Chain_Link']['CAD_Chain_Link_id'] = layerObj.fsty_cad_chain_link.CAD_Chain_Link_id
        jsonLayerObj['FSTY_CAD_Chain_Link']['CAD_Chain_Link_course'] = layerObj.fsty_cad_chain_link.CAD_Chain_Link_course
        jsonLayerList.append(jsonLayerObj)


    jsonDesignObj['CAD_Design_Data_id'] = designObj.CAD_Design_Data_id
    jsonDesignObj['CAD_Design_Data_name'] = designObj.CAD_Design_Data_name
    jsonDesignObj['CAD_Design_Data_code'] = designObj.CAD_Design_Data_code
    jsonDesignObj['CAD_Design_Data_pattern_image'] = designObj.CAD_Design_Data_pattern_image.url
    jsonDesignObj['CAD_Design_Data_simulation_image']= designObj.CAD_Design_Data_simulation_image.url
    jsonDesignObj['CAD_Design_Data_create_date'] = designObj.CAD_Design_Data_create_date.strftime("%Y-%m-%d")
    jsonDesignObj['CAD_Design_Data_magnification'] = designObj.CAD_Design_Data_magnification
    jsonDesignObj['FSTY_CAD_Production'] = {}
    jsonDesignObj['FSTY_CAD_Production']['CAD_Production_id'] = designObj.fsty_cad_production.CAD_Production_id
    jsonDesignObj['FSTY_CAD_Production']['CAD_Production_quota_per_day'] = designObj.fsty_cad_production.CAD_Production_quota_per_day
    jsonDesignObj['FSTY_CAD_Production']['CAD_Production_machine_name'] = designObj.fsty_cad_production.CAD_Production_machine_name
    jsonDesignObj['FSTY_CAD_Production']['CAD_Production_note'] = designObj.fsty_cad_production.CAD_Production_note
    jsonDesignObj['FSTY_CAD_Production']['FSTY_CAD_Fabric'] = jsonFabricList
    jsonDesignObj['FSTY_CAD_Layer'] = jsonLayerList

    return HttpResponse(json.dumps(jsonDesignObj), content_type='application/json')

@login_required(login_url='/')
@csrf_exempt
def delete(request):

    designId = request.POST.get("designId", None)

    if designId != None:
        designObj = FSTY_CAD_Design_Data.objects.get(CAD_Design_Data_id=designId)
        designObj.delete()

    return HttpResponse(json.dumps('{success: true}'), content_type='application/json')

@csrf_exempt
@login_required(login_url='/')
def showList(request):

    designList = FSTY_CAD_Design_Data.objects.all().order_by("-CAD_Design_Data_id")
    orderList = Order.objects.all()

    return render(request, 'designList.html', {'designList': designList, 'count': designList.count(), 'title': 'Design','orderList':orderList, 'userlang':request.user})

@csrf_exempt
@login_required(login_url='/')
def showDesign(request, designId):
    designObj = FSTY_CAD_Design_Data.objects.get(CAD_Design_Data_id=designId)

    return render(request, 'designDetail.html', {'object': designObj, 'title': 'Design', 'userlang':request.user})

@csrf_exempt
@login_required(login_url='/')
def showDesignProduction(request, designId):

    designObj = FSTY_CAD_Design_Data.objects.get(CAD_Design_Data_id=designId)

    return render(request, 'worksheet/knit.html', {'object': designObj, 'userlang':request.user})


@csrf_exempt
def designListByJson(request):
    searchName = request.POST['searchName']

    designList = FSTY_CAD_Design_Data.objects.filter(CAD_Design_Data_name__contains=searchName).order_by('-CAD_Design_Data_id')
    jsonList = []
    for obj in designList:
        jsonObj = {}
        jsonObj['id'] = obj.CAD_Design_Data_id
        jsonObj['name'] = obj.CAD_Design_Data_name
        jsonObj['date'] = obj.CAD_Design_Data_create_date.strftime("%Y-%m-%d")
        jsonList.append(jsonObj)

    return HttpResponse(json.dumps(jsonList), content_type='application/json')

# Create your views here.
@csrf_exempt
def upload(request):
    if 'project' in request.FILES:

        # file catch
        xml_file = request.FILES['project']
        pattern_image = request.FILES['design']
        simulation_image = request.FILES['simulation']

        # project save
        cad_design_data = FSTY_CAD_Design_Data()
        cad_design_data.save()
        xml_file_name = 'data/project/' + str(cad_design_data.CAD_Design_Data_id) + '/xml/' + xml_file.name
        cad_design_data.CAD_Design_Data_xml.save(xml_file_name, ContentFile(xml_file.read()))

        pattern_image_path = 'data/project/' + str(cad_design_data.CAD_Design_Data_id) + '/img/' + pattern_image.name
        cad_design_data.CAD_Design_Data_pattern_image.save(pattern_image_path, ContentFile(pattern_image.read()))

        simulation_image_path = 'data/project/' + str(cad_design_data.CAD_Design_Data_id) + '/img/' + simulation_image.name
        cad_design_data.CAD_Design_Data_simulation_image.save(simulation_image_path, ContentFile(simulation_image.read()))

        #0506 수정부분 현재 style_for_us_가 작동중이지 않아 넘기는 부분이 없으니 무한 반복으로 인한 코드 진행이 되질않음 추후에 style for us 재구동시 주석문 헤제


        # qr_code_image = qrcode.make('http://211.238.177.143:8888/design_data/'+str(cad_design_data.id)+'/')
        # qr_code_image_path = 'data/project/' + str(cad_design_data.id) + '/img/qr_code_image.png'
        # cad_design_data.qr_code.save(qr_code_image_path, ContentFile(qr_code_image.read()))
        # qr_code_image.save(settings.MEDIA_ROOT + '/data/project/' + str(cad_design_data.id) + '/img/qr_code_image.png')

        project_path = settings.MEDIA_ROOT + '/data/project/' + str(cad_design_data.CAD_Design_Data_id)

        # django 내장 파일업로드 기능이 아닌 부분
        # UPLOAD_DIR = settings.MEDIA_ROOT + 'data/project/' + str(project.id) + '/trc'
        # if not os.path.exists(UPLOAD_DIR):
        #     os.makedirs(UPLOAD_DIR)
        # trc = request.FILES['trc']
        # fp = open('%s/%s' % (UPLOAD_DIR, trc._name), 'wb')
        # for chunk in trc.chunks():
        #     fp.write(chunk)
        # fp.close()

        # django 파일필드 사용 저장
        #trc = request.FILES['trc']
        #trc_name = 'data/project/' + str(cad_design_data.id) + '/trc/' + trc.name
        #cad_design_data.trc_file.save(trc_name, ContentFile(trc.read()))
        with open(settings.MEDIA_ROOT + '/' + cad_design_data.CAD_Design_Data_xml.__str__(), encoding='UTF-8') as xml:
            doc = parse(xml)
        root = doc.getroot()
        cad_design_data.CAD_Design_Data_name = root.get("name")
        cad_design_data.CAD_Design_Data_code = root.get("code")
        cad_design_data.CAD_Design_Data_magnification = root.find("production").find("magnification_ratio").get("value")
        cad_design_data.save()

        # Git 테스트 161205
        # production save
        xml_production = root.find("production")
        cad_production = FSTY_CAD_Production()
        cad_production.CAD_Production_quota_per_day = xml_production.find("quota_per_day").get("value")
        cad_production.CAD_Production_machine_name = xml_production.find("machine_name").get("value")
        cad_production.CAD_Production_note = xml_production.find("note").get("value")

sanup/design_data/templates/design_data/design_data_detail.html
{% extends "base/base.html" %}
{% load staticfiles %}
{% block content %}
        <div id="orderWrap">
            <h2>경편설계도</h2>
            <div>Name : {{ object.CAD_Design_Data_name }}</div>
            <div id="topSecond">
                <div>CODE : {{ object.CAD_Design_Data_code }}</div>
                <div id="date">DATE : {{ object.CAD_Design_Data_create_date|date:"Y-m-d" }}</div>
            </div>
            <table id="yarnTable">
                <colgroup>
                    <col width="5%">
                    <col width="5%">
                    <col width="10%">
                    <col width="13%">
                    <col width="7%">
                    <col width="10%">
                    <col width="10%">
                    <col width="15%">
                    <col width="10%">
                    <col width="5%">
                    <col width="10%">
                </colgroup>
                <tr>
                    <th>BAR</th>
                    <th>사번</th>
                    <th>원사메이커</th>
                    <th>사종</th>
                    <th>색상</th>
                    <th>고유코드</th>
                    <th>비율(%)</th>
                    <th>송출(mm/Rank)</th>
                    <th>본수</th>
                    <th>빔수</th>
                    <th>총본수</th>
                </tr>
                {% for layer in object.fsty_cad_layer_set.all %}
                <tr>
                    <td>{{ layer.CAD_Layer_name }}</td>
                    <td>{{ layer.fsty_cad_yarn.CAD_Yarn_idx }}</td>
                    <td>{{ layer.fsty_cad_yarn.CAD_Yarn_maker }}</td>
                    <td>{{ layer.fsty_cad_yarn.CAD_Yarn_spec }}</td>
                    <td><div class="cadyarn_color" style="background-color:rgb({{ layer.fsty_cad_yarn.CAD_Yarn_rgb_color }}); width:80%; height:15px; border: 1px solid black;"></div></td>
                    <td>{{ layer.fsty_cad_yarn.CAD_Yarn_code }}</td>
                    <td>{{ layer.CAD_Layer_ratio }}</td>
                    <td>{{ layer.CAD_Layer_mm_rack }}</td>
                    <td>{{ layer.CAD_Layer_use }}</td>
                    <td>{{ layer.CAD_Layer_beam }}</td>
                    <td>{{ layer.CAD_Layer_total }}</td>
                </tr>
                {% endfor %}
            </table>

            <table id="fabricTable">
                <colgroup>
                    <col width="20%">
                    <col width="20%">
                    <col width="20%">
                    <col width="20%">
                    <col width="20%">
                </colgroup>
                <tr>
                    <th>원단</th>
                    <th>웨일밀도</th>
                    <th>코스밀도</th>
                    <th>폭</th>
                    <th>중량/폭</th>
                </tr>
                {% for fabric in object.fsty_cad_production.fsty_cad_fabric_set.all %}
                <tr>
                    <td>{% if fabric.CAD_Fabric_type == 'R' %}생지{% else %}가공지{% endif %}</td>
                    <td>{{ fabric.CAD_Fabric_wpi }} w/inch</td>
                    <td>{{ fabric.CAD_Fabric_cpi }} c/cm</td>
                    <td>{{ fabric.CAD_Fabric_width }} inch</td>
                    <td>{{ fabric.CAD_Fabric_weight_per_width }} g/y</td>
                </tr>
                {% endfor %}
            </table>
            <table id="colorTable">
                <colgroup>
                    <col width="10%">
                    <col width="30%">
                    <col width="30%">
                    <col width="30%">
                </colgroup>
                <tr>
                    <th>BAR</th>
                    <th>RGB Color</th>
                    <th>LAB Color</th>
                    <th>Pantone Color</th>
                </tr>
                {% for layer in object.fsty_cad_layer_set.all %}
                <tr>
                    <td>{{ layer.CAD_Layer_name }}</td>
                    <td>{{ layer.fsty_cad_yarn.CAD_Yarn_rgb_color }}</td>
                    <td>{{ layer.fsty_cad_yarn.CAD_Yarn_lab_color }}</td>
                    <td>{{ layer.fsty_cad_yarn.CAD_Yarn_pantone_color }}</td>
                </tr>
                {% endfor %}
            </table>
            <div class="output"><span>일일생산량 :</span> {{ object.fsty_cad_production.CAD_Production_quota_per_day }}</div>
            <div class="machineName"><span>기종 :</span> {{ object.fsty_cad_production.CAD_Production_machine_name }}</div>
            <div>
                {% for layer in object.fsty_cad_layer_set.all %}
                <div>
                    <div class="course"><span>{{ layer.CAD_Layer_name }}</span> {{ layer.fsty_cad_chain_link.CAD_Chain_Link_course }}</div>
                </div>
                {% endfor %}
            </div>
            <div class="array">
                <h3>배열</h3>
                {% for layer in object.fsty_cad_layer_set.all %}
                <div class="inoutData">
                    <div><span>{{ layer.CAD_Layer_name }}</span> {{ layer.CAD_Layer_iodata }}</div>
                </div>
                {% endfor %}
            </div>
            <div id="note">
                <h3>비고</h3>
                <div>{{ object.fsty_cad_production.CAD_Production_note}}</div>
            </div>
            <div id="psBox" class="fix">
                <div>
                    <h4>조직도</h4>
                    <div><img src="{{ object.CAD_Design_Data_pattern_image.url }}"></div>
                </div>

                <div>
                    <h4>배율 : {{ object.CAD_Design_Data_magnification }}</h4>
                    <div><img src="{{ object.CAD_Design_Data_simulation_image.url }}"></div>
                </div>

            </div>
            <div id="qrBox"><img src="{{ object.CAD_Design_Data_qr_code.url }}"></div>
        </div>
    </body>
    </html>
 {% endblock content %}